server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: file://github.com/MeSeurus/GB_Planner_Swagger/blob/core-service/core-service/src/main/resources/application.yaml
